services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379